### ISSUE TITLE
Configure pre-commit hooks

### ISSUE THREAD

**Issue by sfc-gh-twhite** [Snowflake-Labs/semantic-model-generator#155]
There are several commits taking place in each PR to perform linting tasks. 

I would encourage using something like [pre-commit](https://pre-commit.com/) to ensure all standards are upheld appropriately and block commits that introduce violations. 

The initial run on all files will likely introduce several diffs, so we will want to ensure any outstanding PRs are addressed to avoid needing to merge or rebase. 

Here's an example of a pre-commit configuration file as a starting point:

```yml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
```
